import { useState } from 'react';
const baseStyle = { background: '#FDFBF7', border: '1px solid #E5DFD3', borderRadius: 14, padding: '1.25rem', margin: '1.5rem 0', fontFamily: "system-ui, sans-serif" };
export default function AnalogyRLInverseReinforcementLearning() {
  const [idx, setIdx] = useState(0);
  const perspectives = [
    { emoji: '💡', label: 'Core Idea', text: 'Imagine watching a master chef prepare a complex dish. You could try to copy their every move -- chop here, stir there -- but you would fail the moment the recipe changes. Instead, if you understood their underlying goals (balance flavors, achieve certain textures, present beautifully), you could cook any dish well.' },
    { emoji: '⚙️', label: 'How It Works', text: 'Given a set of expert demonstrations &#123;D&#125; = \\&#123;_1, _2, , _M\\&#125; where each trajectory  = (s_0, a_0, s_1, a_1, ) is generated by an expert policy ^*, IRL seeks a reward function R_(s, a) such that:  [equation]  The classic approach (Ng and Russell, 2000) formulates this as finding R such that the expert\'s policy achieves higher value than any other.' },
    { emoji: '🔍', label: 'In Detail', text: 'Standard RL takes a reward function and finds an optimal policy. IRL inverts this: given an optimal (or near-optimal) policy demonstrated through trajectories, it recovers the reward function R that makes the observed behavior optimal.' },
  ];
  return (
    <div style={baseStyle}>
      <p style={{ fontSize: '0.8rem', fontWeight: 700, color: '#2C3E2D', marginBottom: 10, letterSpacing: '0.05em' }}>\u2726 KEY PERSPECTIVES</p>
      <div style={{ display: 'flex', gap: 6, marginBottom: 12, flexWrap: 'wrap' as const }}>
        {perspectives.map((p, i) => (
          <button key={i} onClick={() => setIdx(i)} style={{ padding: '4px 12px', borderRadius: 20, border: idx === i ? '2px solid #8BA888' : '1px solid #E5DFD3', background: idx === i ? '#8BA88818' : 'transparent', fontSize: '0.8rem', cursor: 'pointer', color: '#2C3E2D', fontWeight: idx === i ? 600 : 400 }}>
            {p.emoji} {p.label}
          </button>
        ))}
      </div>
      <p style={{ fontSize: '0.9rem', color: '#3D4F3E', lineHeight: 1.6, margin: 0 }}>{perspectives[idx].text}</p>
    </div>
  );
}
