import { useState } from 'react';
const baseStyle = { background: '#FDFBF7', border: '1px solid #E5DFD3', borderRadius: 14, padding: '1.25rem', margin: '1.5rem 0', fontFamily: 'system-ui, sans-serif' };
export default function AnalogySyntheticData() {
  const [idx, setIdx] = useState(0);
  const analogies = [
    { emoji: '🎮', label: 'Flight Simulator', text: 'Pilots train in flight simulators — synthetic environments that mimic real conditions. Synthetic data for LLMs is similar: AI-generated text that mimics real training data. A stronger model generates examples (math solutions, code, conversations) that a smaller model learns from. This enables training on rare scenarios (edge cases, specialized domains) that are scarce in natural data.' },
    { emoji: '🏭', label: 'Data Factory', text: 'When you cannot mine enough natural diamonds (human data), you manufacture synthetic ones. AI labs use stronger models to generate training data for weaker models at massive scale. Phi-3 was trained primarily on synthetic data generated by GPT-4. The key: synthetic data must be diverse and verified, or you risk model collapse — teaching the student only what the teacher already knows.' },
    { emoji: '🧪', label: 'Lab-Grown', text: 'Lab-grown meat is chemically identical to natural meat but produced in controlled conditions. Synthetic data is similarly "grown" by AI models under controlled conditions: specific prompts, quality filters, and verification steps ensure the output matches or exceeds natural data quality. This is especially powerful for math (verifiable answers), code (executable tests), and instruction-following (scalable generation).' },
  ];
  return (
    <div style={baseStyle}>
      <p style={{ fontSize: '0.8rem', fontWeight: 700, color: '#2C3E2D', marginBottom: 10, letterSpacing: '0.05em' }}>✦ THINK OF IT AS...</p>
      <div style={{ display: 'flex', gap: 6, marginBottom: 12, flexWrap: 'wrap' }}>
        {analogies.map((a, i) => (
          <button key={i} onClick={() => setIdx(i)} style={{ padding: '4px 12px', borderRadius: 20, border: idx === i ? '2px solid #8BA888' : '1px solid #E5DFD3', background: idx === i ? '#8BA888' + '18' : 'transparent', fontSize: '0.8rem', cursor: 'pointer', color: '#2C3E2D', fontWeight: idx === i ? 600 : 400 }}>
            {a.emoji} {a.label}
          </button>
        ))}
      </div>
      <p style={{ fontSize: '0.9rem', color: '#3D4F3E', lineHeight: 1.6, margin: 0 }}>{analogies[idx].text}</p>
    </div>
  );
}
