import { useState } from 'react';
const baseStyle = { background: '#FDFBF7', border: '1px solid #E5DFD3', borderRadius: 14, padding: '1.25rem', margin: '1.5rem 0', fontFamily: "system-ui, sans-serif" };
export default function AnalogyMLFLearningCurves() {
  const [idx, setIdx] = useState(0);
  const perspectives = [
    { emoji: '💡', label: 'Core Idea', text: 'Imagine you are studying for an exam. At first, both your practice scores and your real test scores improve rapidly. Eventually, your practice scores keep climbing (you memorize the practice material), but your real test scores plateau.' },
    { emoji: '⚙️', label: 'How It Works', text: 'Two related but distinct diagnostic plots share the name "learning curve":  Sample learning curve (the classic form): Plots training error and validation error as a function of training set size n. Generated by repeatedly training the model on subsets of increasing size and evaluating on a fixed validation set.' },
    { emoji: '🔍', label: 'In Detail', text: 'Formally, a learning curve is a function E(n) that maps a resource quantity (typically the number of training examples n) to a performance measure (training error, validation error, or both).' },
  ];
  return (
    <div style={baseStyle}>
      <p style={{ fontSize: '0.8rem', fontWeight: 700, color: '#2C3E2D', marginBottom: 10, letterSpacing: '0.05em' }}>\u2726 KEY PERSPECTIVES</p>
      <div style={{ display: 'flex', gap: 6, marginBottom: 12, flexWrap: 'wrap' as const }}>
        {perspectives.map((p, i) => (
          <button key={i} onClick={() => setIdx(i)} style={{ padding: '4px 12px', borderRadius: 20, border: idx === i ? '2px solid #8BA888' : '1px solid #E5DFD3', background: idx === i ? '#8BA88818' : 'transparent', fontSize: '0.8rem', cursor: 'pointer', color: '#2C3E2D', fontWeight: idx === i ? 600 : 400 }}>
            {p.emoji} {p.label}
          </button>
        ))}
      </div>
      <p style={{ fontSize: '0.9rem', color: '#3D4F3E', lineHeight: 1.6, margin: 0 }}>{perspectives[idx].text}</p>
    </div>
  );
}
