import { useState } from 'react';

const baseStyle = {
  fontFamily: "'Source Sans 3', system-ui, sans-serif",
  background: '#FDFBF7',
  border: '1px solid #E5DFD3',
  borderRadius: '14px',
  padding: '2rem',
  margin: '2.5rem 0',
};

const STAGES = [
  {
    title: 'Few-Shot CoT Prompting',
    era: '2022 — Wei et al.',
    approach: 'Manually write step-by-step exemplars in the prompt. The model mimics the reasoning pattern via in-context learning.',
    prompt: '"Q: If a store has 3 boxes with 8 apples each and sells 10, how many remain?\\nA: Let\'s think step by step.\\n3 boxes × 8 apples = 24 total.\\n24 − 10 sold = 14 remain.\\nThe answer is 14.\\n\\nQ: A train travels 60 mph for 2.5 hours..."',
    output: 'Let\'s think step by step.\n60 × 2.5 = 150 miles.\nThe answer is 150 miles.',
    quality: 62,
    qualityLabel: 'Inconsistent — depends on exemplar quality',
    color: '#8BA888',
  },
  {
    title: 'CoT Distillation',
    era: '2023 — Orca, Phi, etc.',
    approach: 'Use a large teacher model (e.g. GPT-4) to generate chain-of-thought traces. Fine-tune a smaller student model on these (input, reasoning, answer) triples.',
    prompt: 'Training data generated by GPT-4:\n{"prompt": "Train at 60 mph for 2.5h",\n "reasoning": "Speed × Time = Distance\\n60 × 2.5 = 150",\n "answer": "150 miles"}',
    output: 'Speed multiplied by time gives distance.\n60 mph × 2.5 hours = 150 miles.\nThe train travels 150 miles.',
    quality: 78,
    qualityLabel: 'Reliable — but bounded by teacher quality',
    color: '#D4A843',
  },
  {
    title: 'RLVR-Trained Reasoning',
    era: '2024-25 — o1, R1, etc.',
    approach: 'Train the model with reinforcement learning using verifiable rewards (RLVR). The model learns to generate and self-correct long reasoning chains. No human-written CoT needed.',
    prompt: 'RL reward signal:\n✓ Final answer matches ground truth → +1\n✗ Wrong answer → 0\nModel learns to allocate "thinking tokens" autonomously.',
    output: '<think>\nI need to find the distance.\nDistance = speed × time.\nLet me verify: 60 × 2.5.\n60 × 2 = 120, 60 × 0.5 = 30.\n120 + 30 = 150. ✓\n</think>\nThe train travels 150 miles.',
    quality: 95,
    qualityLabel: 'Emergent self-correction and verification',
    color: '#C76B4A',
  },
];

export default function CoTTrainingPipeline() {
  const [stage, setStage] = useState(0);
  const s = STAGES[stage];

  return (
    <div style={baseStyle}>
      <div style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
          <span style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '22px', height: '22px', borderRadius: '6px', background: 'rgba(139, 168, 136, 0.15)', fontSize: '12px' }}>▶</span>
          <span style={{ fontSize: '10px', fontWeight: 700, textTransform: 'uppercase' as const, letterSpacing: '0.12em', color: '#6E8B6B' }}>Interactive</span>
        </div>
        <h3 style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: '1.3rem', fontWeight: 600, color: '#2C3E2D', margin: 0 }}>
          Chain-of-Thought Training Evolution
        </h3>
        <p style={{ fontSize: '0.88rem', color: '#5A6B5C', margin: '0.4rem 0 0 0', lineHeight: 1.6 }}>
          Click through three eras showing how models learned to reason step-by-step.
        </p>
      </div>

      <div style={{ display: 'flex', gap: '0.4rem', marginBottom: '1.25rem' }}>
        {STAGES.map((st, i) => (
          <button key={st.title} onClick={() => setStage(i)} style={{
            flex: 1, padding: '0.5rem 0.5rem', borderRadius: '6px',
            border: `1px solid ${stage === i ? s.color : '#E5DFD3'}`,
            background: stage === i ? `${s.color}11` : 'transparent',
            color: stage === i ? s.color : '#5A6B5C',
            fontWeight: stage === i ? 600 : 400,
            fontSize: '0.72rem', cursor: 'pointer', fontFamily: "'Source Sans 3', sans-serif",
            transition: 'all 0.2s ease',
          }}>
            Stage {i + 1}
          </button>
        ))}
      </div>

      <div style={{ background: '#F0EBE1', borderRadius: '8px', padding: '1rem', marginBottom: '0.75rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: '0.5rem' }}>
          <span style={{ fontFamily: "'Source Serif 4', serif", fontSize: '1rem', fontWeight: 600, color: '#2C3E2D' }}>{s.title}</span>
          <span style={{ fontSize: '0.7rem', color: '#7A8B7C', fontFamily: "'JetBrains Mono', monospace" }}>{s.era}</span>
        </div>
        <p style={{ fontSize: '0.82rem', color: '#5A6B5C', lineHeight: 1.6, margin: '0 0 0.75rem 0' }}>{s.approach}</p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem', marginBottom: '0.75rem' }}>
        <div style={{ background: '#F0EBE1', borderRadius: '8px', padding: '0.75rem' }}>
          <div style={{ fontSize: '0.65rem', color: '#7A8B7C', textTransform: 'uppercase' as const, letterSpacing: '0.05em', fontWeight: 600, marginBottom: '0.4rem' }}>
            {stage === 2 ? 'Training Signal' : 'Input / Prompt'}
          </div>
          <pre style={{ fontSize: '0.7rem', color: '#2C3E2D', fontFamily: "'JetBrains Mono', monospace", whiteSpace: 'pre-wrap', margin: 0, lineHeight: 1.5 }}>{s.prompt}</pre>
        </div>
        <div style={{ background: '#F0EBE1', borderRadius: '8px', padding: '0.75rem' }}>
          <div style={{ fontSize: '0.65rem', color: '#7A8B7C', textTransform: 'uppercase' as const, letterSpacing: '0.05em', fontWeight: 600, marginBottom: '0.4rem' }}>Model Output</div>
          <pre style={{ fontSize: '0.7rem', color: '#2C3E2D', fontFamily: "'JetBrains Mono', monospace", whiteSpace: 'pre-wrap', margin: 0, lineHeight: 1.5 }}>{s.output}</pre>
        </div>
      </div>

      <div style={{ background: '#F0EBE1', borderRadius: '8px', padding: '0.75rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.4rem' }}>
          <span style={{ fontSize: '0.65rem', color: '#7A8B7C', textTransform: 'uppercase' as const, letterSpacing: '0.05em', fontWeight: 600 }}>Reasoning Quality</span>
          <span style={{ fontSize: '0.75rem', fontFamily: "'JetBrains Mono', monospace", color: s.color, fontWeight: 600 }}>{s.quality}%</span>
        </div>
        <div style={{ width: '100%', height: '8px', background: '#E5DFD3', borderRadius: '4px', overflow: 'hidden' }}>
          <div style={{ width: `${s.quality}%`, height: '100%', background: s.color, borderRadius: '4px', transition: 'width 0.5s ease' }} />
        </div>
        <div style={{ fontSize: '0.72rem', color: '#5A6B5C', marginTop: '0.35rem' }}>{s.qualityLabel}</div>
      </div>
    </div>
  );
}
