import { useState } from 'react';

const DETAILS = [
    { label: 'Convergence', detail: 'SARSA converges to Q^ (Q-values of the current policy) under standard Robbins-Monro conditions. With a GLIE policy (  0), it converges to Q^*.' },
    { label: 'On-policy data requirement', detail: 'SARSA cannot effectively learn from data generated by a different policy (unlike Q-learning). Replaying old experience is problematic because the data distribution no longer matches the current policy.' },
    { label: 'Variance', detail: 'Standard SARSA has higher per-update variance than Expected SARSA because A_&#123;t+1&#125; is sampled. Lower variance than MC because only one-step sampling is involved.' },
    { label: 'Step size sensitivity', detail: 'SARSA is generally less sensitive to the choice of  than Q-learning, because its targets are less noisy (no  operator amplifying estimation errors).' },
    { label: 'Expected SARSA cost', detail: 'O() per update vs O(1) for SARSA and Q-learning, but the improved stability often allows larger  values, leading to faster overall learning.' },
    { label: 'Safety advantage', detail: 'In environments with catastrophic states (cliffs, obstacles), SARSA\'s on-policy nature produces more conservative, often safer, behavior during training.' },
];

export default function ExplorerRLSarsa() {
  const [open, setOpen] = useState<number | null>(null);

  return (
    <div style={{ fontFamily: "'Source Sans 3', system-ui, sans-serif", background: '#FDFBF7', border: '1px solid #E5DFD3', borderRadius: '14px', padding: '2rem', margin: '2.5rem 0' }}>
      <div style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
          <span style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '22px', height: '22px', borderRadius: '6px', background: 'rgba(139, 168, 136, 0.15)', fontSize: '12px' }}>&#9654;</span>
          <span style={{ fontSize: '10px', fontWeight: 700, textTransform: 'uppercase' as const, letterSpacing: '0.12em', color: '#6E8B6B' }}>Interactive</span>
        </div>
        <h3 style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: '1.3rem', fontWeight: 600, color: '#2C3E2D', margin: 0 }}>
          SARSA \u2014 Key Details Explorer
        </h3>
        <p style={{ fontSize: '0.88rem', color: '#5A6B5C', margin: '0.4rem 0 0 0', lineHeight: 1.6 }}>
          Click each card to explore the technical details.
        </p>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
        {DETAILS.map((d, i) => (
          <button key={i} onClick={() => setOpen(open === i ? null : i)} style={{
            textAlign: 'left' as const, background: open === i ? '#F0EBE1' : '#FDFBF7', border: '1px solid #E5DFD3',
            borderRadius: '10px', padding: '0.875rem 1rem', cursor: 'pointer', width: '100%', transition: 'background 0.2s ease',
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <span style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: '0.95rem', fontWeight: 600, color: '#2C3E2D' }}>
                {d.label}
              </span>
              <span style={{ fontSize: '0.8rem', color: '#7A8B7C', transform: open === i ? 'rotate(90deg)' : 'none', transition: 'transform 0.2s ease' }}>
                &#9654;
              </span>
            </div>
            {open === i && (
              <p style={{ fontSize: '0.85rem', color: '#5A6B5C', lineHeight: 1.6, margin: '0.5rem 0 0 0' }}>
                {d.detail}
              </p>
            )}
          </button>
        ))}
      </div>
    </div>
  );
}
