import { useState } from 'react';

const baseStyle = {
  fontFamily: "'Source Sans 3', system-ui, sans-serif",
  background: '#FDFBF7',
  border: '1px solid #E5DFD3',
  borderRadius: '14px',
  padding: '2rem',
  margin: '2.5rem 0',
};

const BIASES = [
  {
    name: 'Position Bias',
    desc: 'LLM judges disproportionately favor whichever response appears first (or sometimes second). Simply swapping the order changes the verdict.',
    example: {
      prompt: 'What causes rain?',
      outputA: 'Rain occurs when water vapor in the atmosphere condenses into droplets that become heavy enough to fall.',
      outputB: 'When warm, moist air rises and cools, the water vapor condenses around tiny particles forming clouds. When droplets grow large enough, gravity pulls them down as rain.',
      verdictOriginal: 'A',
      verdictSwapped: 'B',
      note: 'Same outputs, but whichever is shown first gets picked. The judge anchors to the first response it reads.',
    },
    mitigation: 'Run evaluations twice with swapped positions and only count cases where both orderings agree.',
    severity: 0.8,
  },
  {
    name: 'Verbosity Bias',
    desc: 'LLM judges systematically prefer longer, more detailed responses even when the shorter answer is more accurate or appropriate.',
    example: {
      prompt: 'What is 2 + 2?',
      outputA: '4',
      outputB: 'To solve this arithmetic problem, we need to consider the fundamental properties of addition in mathematics. When we add 2 and 2, we are combining two groups of two units each. Using the standard rules of arithmetic, 2 + 2 equals 4. This is one of the most basic addition facts that forms the foundation of mathematical reasoning.',
      verdictOriginal: 'B',
      verdictSwapped: 'B',
      note: 'The judge picks the verbose answer even though "4" is perfectly correct and appropriate. More words does not equal better quality.',
    },
    mitigation: 'Include length-controlled pairs in evaluation sets. Instruct the judge to penalize unnecessary verbosity.',
    severity: 0.7,
  },
  {
    name: 'Self-Enhancement Bias',
    desc: 'When an LLM judges outputs from itself vs. another model, it tends to prefer its own outputs due to similar style and phrasing patterns.',
    example: {
      prompt: 'Explain gravity briefly.',
      outputA: 'Gravity is the fundamental force of attraction between objects with mass. It keeps planets in orbit and causes objects to fall toward Earth. Einstein showed it\'s actually the curvature of spacetime caused by mass.',
      outputB: 'Gravity is a natural phenomenon by which all things with mass are brought toward one another. On Earth, gravity gives weight to physical objects and causes the tides. It\'s described by general relativity as curved spacetime.',
      verdictOriginal: 'A',
      verdictSwapped: 'A',
      note: 'Output A was generated by the same model family as the judge. The judge recognizes and prefers its own stylistic patterns.',
    },
    mitigation: 'Use a different model as judge than the models being evaluated. Cross-evaluate with multiple judge models.',
    severity: 0.6,
  },
];

export default function JudgeBiasExplorer() {
  const [biasIdx, setBiasIdx] = useState(0);
  const [showSwapped, setShowSwapped] = useState(false);

  const bias = BIASES[biasIdx];
  const ex = bias.example;

  return (
    <div style={baseStyle}>
      <div style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
          <span style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '22px', height: '22px', borderRadius: '6px', background: 'rgba(139, 168, 136, 0.15)', fontSize: '12px' }}>&#9654;</span>
          <span style={{ fontSize: '10px', fontWeight: 700, textTransform: 'uppercase' as const, letterSpacing: '0.12em', color: '#6E8B6B' }}>Interactive</span>
        </div>
        <h3 style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: '1.3rem', fontWeight: 600, color: '#2C3E2D', margin: 0 }}>
          LLM Judge Bias Explorer
        </h3>
        <p style={{ fontSize: '0.88rem', color: '#5A6B5C', margin: '0.4rem 0 0 0', lineHeight: 1.6 }}>
          Explore three common biases in LLM-as-judge evaluation with concrete examples.
        </p>
      </div>

      <div style={{ display: 'flex', gap: '0.4rem', marginBottom: '1.25rem', flexWrap: 'wrap' }}>
        {BIASES.map((b, i) => (
          <button key={b.name} onClick={() => { setBiasIdx(i); setShowSwapped(false); }} style={{
            padding: '0.35rem 0.7rem', borderRadius: '6px',
            border: `1px solid ${biasIdx === i ? '#C76B4A' : '#E5DFD3'}`,
            background: biasIdx === i ? 'rgba(199,107,74,0.08)' : 'transparent',
            color: biasIdx === i ? '#C76B4A' : '#5A6B5C',
            fontWeight: biasIdx === i ? 600 : 400, fontSize: '0.78rem', cursor: 'pointer',
          }}>
            {b.name}
          </button>
        ))}
      </div>

      <div style={{ background: '#F0EBE1', borderRadius: '8px', padding: '1rem', marginBottom: '1rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '0.5rem' }}>
          <div>
            <div style={{ fontSize: '0.95rem', color: '#2C3E2D', fontWeight: 600 }}>{bias.name}</div>
            <div style={{ fontSize: '0.78rem', color: '#5A6B5C', lineHeight: 1.5, marginTop: '0.2rem' }}>{bias.desc}</div>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', flexShrink: 0, marginLeft: '1rem' }}>
            <span style={{ fontSize: '0.6rem', color: '#7A8B7C', fontWeight: 600, textTransform: 'uppercase' }}>Severity</span>
            <div style={{ display: 'flex', gap: '2px' }}>
              {[1, 2, 3, 4, 5].map(i => (
                <div key={i} style={{ width: '8px', height: '14px', borderRadius: '2px', background: i <= bias.severity * 5 ? '#C76B4A' : '#E5DFD3' }} />
              ))}
            </div>
          </div>
        </div>
      </div>

      <div style={{ background: '#F0EBE1', borderRadius: '8px', padding: '0.75rem 1rem', marginBottom: '0.75rem' }}>
        <div style={{ fontSize: '0.65rem', color: '#7A8B7C', fontWeight: 600, textTransform: 'uppercase' }}>Prompt</div>
        <div style={{ fontSize: '0.85rem', color: '#2C3E2D', fontWeight: 500, marginTop: '0.15rem' }}>{ex.prompt}</div>
      </div>

      {biasIdx === 0 && (
        <div style={{ display: 'flex', gap: '0.4rem', marginBottom: '0.75rem' }}>
          <button onClick={() => setShowSwapped(false)} style={{
            padding: '0.25rem 0.5rem', borderRadius: '5px', fontSize: '0.68rem', cursor: 'pointer',
            border: `1px solid ${!showSwapped ? '#C76B4A' : '#E5DFD3'}`,
            background: !showSwapped ? 'rgba(199,107,74,0.08)' : 'transparent',
            color: !showSwapped ? '#C76B4A' : '#7A8B7C', fontWeight: !showSwapped ? 600 : 400,
          }}>
            Original Order
          </button>
          <button onClick={() => setShowSwapped(true)} style={{
            padding: '0.25rem 0.5rem', borderRadius: '5px', fontSize: '0.68rem', cursor: 'pointer',
            border: `1px solid ${showSwapped ? '#C76B4A' : '#E5DFD3'}`,
            background: showSwapped ? 'rgba(199,107,74,0.08)' : 'transparent',
            color: showSwapped ? '#C76B4A' : '#7A8B7C', fontWeight: showSwapped ? 600 : 400,
          }}>
            Swapped Order
          </button>
        </div>
      )}

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.75rem', marginBottom: '1rem' }}>
        {[
          { label: showSwapped ? 'Position 1 (was B)' : 'Position 1 (A)', text: showSwapped ? ex.outputB : ex.outputA },
          { label: showSwapped ? 'Position 2 (was A)' : 'Position 2 (B)', text: showSwapped ? ex.outputA : ex.outputB },
        ].map(item => (
          <div key={item.label} style={{ background: '#FDFBF7', borderRadius: '8px', padding: '0.75rem', border: '1px solid #E5DFD3' }}>
            <div style={{ fontSize: '0.65rem', color: '#7A8B7C', fontWeight: 600, marginBottom: '0.3rem', textTransform: 'uppercase' }}>{item.label}</div>
            <div style={{ fontSize: '0.78rem', color: '#2C3E2D', lineHeight: 1.6 }}>{item.text}</div>
          </div>
        ))}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem', marginBottom: '1rem' }}>
        <div style={{ background: 'rgba(199,107,74,0.08)', borderRadius: '8px', padding: '0.75rem', border: '1px solid rgba(199,107,74,0.2)' }}>
          <div style={{ fontSize: '0.65rem', color: '#7A8B7C', fontWeight: 600, textTransform: 'uppercase' }}>Judge Verdict</div>
          <div style={{ fontSize: '1rem', fontFamily: "'JetBrains Mono', monospace", color: '#C76B4A', fontWeight: 700, marginTop: '0.15rem' }}>
            Prefers {showSwapped ? ex.verdictSwapped : ex.verdictOriginal}
            {biasIdx === 0 && showSwapped && ex.verdictOriginal !== ex.verdictSwapped && (
              <span style={{ fontSize: '0.65rem', color: '#C76B4A', fontWeight: 500, marginLeft: '0.3rem' }}>(flipped!)</span>
            )}
          </div>
        </div>
        <div style={{ background: '#F0EBE1', borderRadius: '8px', padding: '0.75rem' }}>
          <div style={{ fontSize: '0.65rem', color: '#7A8B7C', fontWeight: 600, textTransform: 'uppercase' }}>Bias Explanation</div>
          <div style={{ fontSize: '0.72rem', color: '#5A6B5C', lineHeight: 1.5, marginTop: '0.15rem' }}>{ex.note}</div>
        </div>
      </div>

      <div style={{ padding: '0.6rem 0.75rem', background: 'rgba(139,168,136,0.08)', borderRadius: '8px', border: '1px solid rgba(139,168,136,0.2)' }}>
        <div style={{ fontSize: '0.7rem', color: '#8BA888', fontWeight: 600, marginBottom: '0.15rem' }}>Mitigation</div>
        <div style={{ fontSize: '0.72rem', color: '#5A6B5C', lineHeight: 1.5 }}>{bias.mitigation}</div>
      </div>
    </div>
  );
}
