import { useState } from 'react';

const STEPS = [
    { title: '1. Naive Reward Shaping and Its Dangers', desc: 'The simplest approach adds a hand-designed bonus F(s, a, s\') to the environment reward:  [equation]  But this changes the MDP, and the optimal policy under R\' may differ from the optimal policy under R.' },
    { title: '2. Potential-Based Reward Shaping (PBRS)', desc: 'The breakthrough result of Ng, Harada, and Russell (1999) identified the only form of reward shaping guaranteed to preserve the optimal policy. If the shaping reward is the difference of a potential function : S  &#123;R&#125;:  [equation]  then the optimal policy under the shaped reward R\' = R + F is.' },
    { title: '3. Choosing the Potential Function', desc: 'The ideal potential function is (s) = V^(s) -- the true optimal value function. This would make the shaped reward equivalent to the advantage function, providing maximal learning signal.' },
    { title: '4. Reward Hacking', desc: 'Reward hacking occurs when the agent finds a way to maximize the shaped reward without actually achieving the intended goal. Famous examples include:  A boat racing agent that found it could earn more reward by collecting bonus tokens in circles than by finishing the race (OpenAI,.' },
    { title: '5. Intrinsic vs. Extrinsic Rewards', desc: 'Reward shaping connects to the broader distinction between extrinsic rewards (from the environment/task) and intrinsic rewards (internally generated by the agent). Intrinsic rewards include:  Curiosity signals: prediction error as reward (detailed in curiosity-driven-exploration.' },
    { title: '6. Curriculum Through Rewards', desc: 'Reward shaping can implement a curriculum -- gradually increasing task difficulty by adjusting the shaping function over training. Early in training, dense shaped rewards guide the agent toward approximate solutions.' },
];

export default function WalkthroughRLRewardShaping() {
  const [step, setStep] = useState(0);
  const current = STEPS[step];

  return (
    <div style={{ fontFamily: "'Source Sans 3', system-ui, sans-serif", background: '#FDFBF7', border: '1px solid #E5DFD3', borderRadius: '14px', padding: '2rem', margin: '2.5rem 0' }}>
      <div style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
          <span style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '22px', height: '22px', borderRadius: '6px', background: 'rgba(139, 168, 136, 0.15)', fontSize: '12px' }}>&#9654;</span>
          <span style={{ fontSize: '10px', fontWeight: 700, textTransform: 'uppercase' as const, letterSpacing: '0.12em', color: '#6E8B6B' }}>Interactive Walkthrough</span>
        </div>
        <h3 style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: '1.3rem', fontWeight: 600, color: '#2C3E2D', margin: 0 }}>
          Reward Shaping \u2014 Step by Step
        </h3>
        <p style={{ fontSize: '0.88rem', color: '#5A6B5C', margin: '0.4rem 0 0 0', lineHeight: 1.6 }}>
          Walk through how reward shaping works, one stage at a time.
        </p>
      </div>

      <div style={{ display: 'flex', gap: '0.35rem', marginBottom: '1.25rem' }}>
        {STEPS.map((_, i) => (
          <button key={i} onClick={() => setStep(i)} style={{
            flex: 1, height: '4px', borderRadius: '2px',
            background: i <= step ? '#C76B4A' : '#E5DFD3',
            border: 'none', cursor: 'pointer', transition: 'background 0.2s ease',
          }} />
        ))}
      </div>

      <div style={{ marginBottom: '1.25rem' }}>
        <h4 style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: '1.05rem', fontWeight: 600, color: '#2C3E2D', margin: '0 0 0.4rem 0' }}>
          {current.title}
        </h4>
        <p style={{ fontSize: '0.85rem', color: '#5A6B5C', lineHeight: 1.6, margin: 0 }}>
          {current.desc}
        </p>
      </div>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <button onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0} style={{
          padding: '0.4rem 1rem', borderRadius: '6px', border: '1px solid #E5DFD3',
          background: step === 0 ? '#F5F0E8' : '#FDFBF7', color: step === 0 ? '#B0A898' : '#5A6B5C',
          fontSize: '0.8rem', cursor: step === 0 ? 'default' : 'pointer', fontFamily: "'Source Sans 3', system-ui, sans-serif",
        }}>
          &#8592; Previous
        </button>
        <span style={{ fontSize: '0.75rem', color: '#7A8B7C', fontFamily: "'JetBrains Mono', monospace" }}>
          {step + 1} / {STEPS.length}
        </span>
        <button onClick={() => setStep(Math.min(STEPS.length - 1, step + 1))} disabled={step === STEPS.length - 1} style={{
          padding: '0.4rem 1rem', borderRadius: '6px',
          border: `1px solid ${step === STEPS.length - 1 ? '#E5DFD3' : '#C76B4A'}`,
          background: step === STEPS.length - 1 ? '#F5F0E8' : 'rgba(199, 107, 74, 0.08)',
          color: step === STEPS.length - 1 ? '#B0A898' : '#C76B4A',
          fontSize: '0.8rem', fontWeight: 500, cursor: step === STEPS.length - 1 ? 'default' : 'pointer',
          fontFamily: "'Source Sans 3', system-ui, sans-serif",
        }}>
          Next &#8594;
        </button>
      </div>
    </div>
  );
}
