import { useState } from 'react';

const STEPS = [
    { title: '1. The IRL Problem', desc: 'Given a set of expert demonstrations &#123;D&#125; = \\&#123;_1, _2, , _M\\&#125; where each trajectory  = (s_0, a_0, s_1, a_1, ) is generated by an expert policy ^*, IRL seeks a reward function R_(s, a) such that:  [equation]  The classic approach (Ng and Russell, 2000) formulates this as finding R such that the.' },
    { title: '2. Feature Matching and Reward Ambiguity', desc: 'Early IRL methods represent the reward as a linear combination of features: R_(s, a) = ^T (s, a). The key insight is that a policy\'s expected return depends only on its feature expectations:  [equation]  IRL then seeks  such that ^T (^*)  ^T () for all .' },
    { title: '3. Maximum Entropy IRL', desc: 'Maximum entropy IRL (Ziebart et al., 2008) resolves the ambiguity elegantly by assuming the expert follows a Boltzmann-rational policy where the probability of a trajectory is exponential in its return:  [equation]  where Z() = _ (_t R_(s_t, a_t)) is the partition function.' },
    { title: '4. Bayesian IRL', desc: 'Bayesian IRL (Ramachandran and Amir, 2007) maintains a posterior distribution over reward functions:  [equation]  where the likelihood P(&#123;D&#125;  R) assumes the expert is Boltzmann-rational with temperature : P(a  s, R)  ( \\, Q^R(s, a)).' },
    { title: '5. Generative Adversarial Imitation Learning (GAIL)', desc: 'GAIL (Ho and Ermon, 2016) connects IRL to generative adversarial networks. A discriminator D_(s, a) distinguishes expert state-action pairs from those generated by the learned policy, while the policy (generator) _ tries to fool the discriminator:  [equation]  The critical insight is that -(1 -.' },
    { title: '6. Connection to RLHF', desc: 'Reinforcement Learning from Human Feedback (RLHF) applies IRL principles to language models. Instead of full demonstrations, humans provide preferences between pairs of outputs.' },
];

export default function WalkthroughRLInverseReinforcementLearning() {
  const [step, setStep] = useState(0);
  const current = STEPS[step];

  return (
    <div style={{ fontFamily: "'Source Sans 3', system-ui, sans-serif", background: '#FDFBF7', border: '1px solid #E5DFD3', borderRadius: '14px', padding: '2rem', margin: '2.5rem 0' }}>
      <div style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
          <span style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '22px', height: '22px', borderRadius: '6px', background: 'rgba(139, 168, 136, 0.15)', fontSize: '12px' }}>&#9654;</span>
          <span style={{ fontSize: '10px', fontWeight: 700, textTransform: 'uppercase' as const, letterSpacing: '0.12em', color: '#6E8B6B' }}>Interactive Walkthrough</span>
        </div>
        <h3 style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: '1.3rem', fontWeight: 600, color: '#2C3E2D', margin: 0 }}>
          Inverse Reinforcement Learning \u2014 Step by Step
        </h3>
        <p style={{ fontSize: '0.88rem', color: '#5A6B5C', margin: '0.4rem 0 0 0', lineHeight: 1.6 }}>
          Walk through how inverse reinforcement learning works, one stage at a time.
        </p>
      </div>

      <div style={{ display: 'flex', gap: '0.35rem', marginBottom: '1.25rem' }}>
        {STEPS.map((_, i) => (
          <button key={i} onClick={() => setStep(i)} style={{
            flex: 1, height: '4px', borderRadius: '2px',
            background: i <= step ? '#C76B4A' : '#E5DFD3',
            border: 'none', cursor: 'pointer', transition: 'background 0.2s ease',
          }} />
        ))}
      </div>

      <div style={{ marginBottom: '1.25rem' }}>
        <h4 style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: '1.05rem', fontWeight: 600, color: '#2C3E2D', margin: '0 0 0.4rem 0' }}>
          {current.title}
        </h4>
        <p style={{ fontSize: '0.85rem', color: '#5A6B5C', lineHeight: 1.6, margin: 0 }}>
          {current.desc}
        </p>
      </div>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <button onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0} style={{
          padding: '0.4rem 1rem', borderRadius: '6px', border: '1px solid #E5DFD3',
          background: step === 0 ? '#F5F0E8' : '#FDFBF7', color: step === 0 ? '#B0A898' : '#5A6B5C',
          fontSize: '0.8rem', cursor: step === 0 ? 'default' : 'pointer', fontFamily: "'Source Sans 3', system-ui, sans-serif",
        }}>
          &#8592; Previous
        </button>
        <span style={{ fontSize: '0.75rem', color: '#7A8B7C', fontFamily: "'JetBrains Mono', monospace" }}>
          {step + 1} / {STEPS.length}
        </span>
        <button onClick={() => setStep(Math.min(STEPS.length - 1, step + 1))} disabled={step === STEPS.length - 1} style={{
          padding: '0.4rem 1rem', borderRadius: '6px',
          border: `1px solid ${step === STEPS.length - 1 ? '#E5DFD3' : '#C76B4A'}`,
          background: step === STEPS.length - 1 ? '#F5F0E8' : 'rgba(199, 107, 74, 0.08)',
          color: step === STEPS.length - 1 ? '#B0A898' : '#C76B4A',
          fontSize: '0.8rem', fontWeight: 500, cursor: step === STEPS.length - 1 ? 'default' : 'pointer',
          fontFamily: "'Source Sans 3', system-ui, sans-serif",
        }}>
          Next &#8594;
        </button>
      </div>
    </div>
  );
}
