import { useState } from 'react';

const STEPS = [
    { title: '1. Self-Instruct: The Bootstrap (2022)', desc: 'Self-Instruct (Wang et al., December 2022) introduced the core idea: start with a small seed set of 175 hand-written instruction-response pairs, then use an LLM to generate new instructions, classify them, generate inputs, and produce outputs.' },
    { title: '2. The Alpaca Moment: Proving It Works (2023)', desc: 'Stanford\'s Alpaca (March 2023) applied Self-Instruct at commercial scale: 52,000 instructions generated by GPT-3.5-turbo for approximately $600, used to fine-tune LLaMA-7B.' },
    { title: '3. Evol-Instruct: Systematically Increasing Complexity (2023)', desc: 'WizardLM\'s Evol-Instruct (Xu et al., April 2023) refined the approach by iteratively evolving simple instructions into complex ones. Starting from a base instruction like "Write a function to sort a list," the LLM applies transformations:  Add constraints: "...' },
    { title: '4. Reasoning Trace Distillation (2023-2025)', desc: 'Orca (Microsoft, June 2023) demonstrated that distilling reasoning traces — not just final answers — from GPT-4 could teach smaller models to reason. Training data included step-by-step explanations showing the process: "To solve this, first I need to identify the variables...' },
    { title: '5. "Textbooks Are All You Need" (2023-2024)', desc: 'Microsoft\'s Phi series represented the most radical vision of synthetic data. Phi-1 (June 2023) trained a 1.3B parameter code model primarily on synthetic "textbook-quality" data generated by GPT-3.5 and GPT-4.' },
    { title: '6. Synthetic Preference Data and Self-Play (2024)', desc: 'For alignment, synthetic data has become equally transformative. In the RLAIF approach (Constitutional AI), an LLM generates preference judgments instead of human annotators.' },
];

export default function WalkthroughLLE06TheSyntheticDataRevolution() {
  const [step, setStep] = useState(0);
  const current = STEPS[step];

  return (
    <div style={{ fontFamily: "'Source Sans 3', system-ui, sans-serif", background: '#FDFBF7', border: '1px solid #E5DFD3', borderRadius: '14px', padding: '2rem', margin: '2.5rem 0' }}>
      <div style={{ marginBottom: '1.5rem' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem' }}>
          <span style={{ display: 'inline-flex', alignItems: 'center', justifyContent: 'center', width: '22px', height: '22px', borderRadius: '6px', background: 'rgba(139, 168, 136, 0.15)', fontSize: '12px' }}>&#9654;</span>
          <span style={{ fontSize: '10px', fontWeight: 700, textTransform: 'uppercase' as const, letterSpacing: '0.12em', color: '#6E8B6B' }}>Interactive Walkthrough</span>
        </div>
        <h3 style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: '1.3rem', fontWeight: 600, color: '#2C3E2D', margin: 0 }}>
          The Synthetic Data Revolution \u2014 Step by Step
        </h3>
        <p style={{ fontSize: '0.88rem', color: '#5A6B5C', margin: '0.4rem 0 0 0', lineHeight: 1.6 }}>
          Walk through how the synthetic data revolution works, one stage at a time.
        </p>
      </div>

      <div style={{ display: 'flex', gap: '0.35rem', marginBottom: '1.25rem' }}>
        {STEPS.map((_, i) => (
          <button key={i} onClick={() => setStep(i)} style={{
            flex: 1, height: '4px', borderRadius: '2px',
            background: i <= step ? '#C76B4A' : '#E5DFD3',
            border: 'none', cursor: 'pointer', transition: 'background 0.2s ease',
          }} />
        ))}
      </div>

      <div style={{ marginBottom: '1.25rem' }}>
        <h4 style={{ fontFamily: "'Source Serif 4', Georgia, serif", fontSize: '1.05rem', fontWeight: 600, color: '#2C3E2D', margin: '0 0 0.4rem 0' }}>
          {current.title}
        </h4>
        <p style={{ fontSize: '0.85rem', color: '#5A6B5C', lineHeight: 1.6, margin: 0 }}>
          {current.desc}
        </p>
      </div>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <button onClick={() => setStep(Math.max(0, step - 1))} disabled={step === 0} style={{
          padding: '0.4rem 1rem', borderRadius: '6px', border: '1px solid #E5DFD3',
          background: step === 0 ? '#F5F0E8' : '#FDFBF7', color: step === 0 ? '#B0A898' : '#5A6B5C',
          fontSize: '0.8rem', cursor: step === 0 ? 'default' : 'pointer', fontFamily: "'Source Sans 3', system-ui, sans-serif",
        }}>
          &#8592; Previous
        </button>
        <span style={{ fontSize: '0.75rem', color: '#7A8B7C', fontFamily: "'JetBrains Mono', monospace" }}>
          {step + 1} / {STEPS.length}
        </span>
        <button onClick={() => setStep(Math.min(STEPS.length - 1, step + 1))} disabled={step === STEPS.length - 1} style={{
          padding: '0.4rem 1rem', borderRadius: '6px',
          border: `1px solid ${step === STEPS.length - 1 ? '#E5DFD3' : '#C76B4A'}`,
          background: step === STEPS.length - 1 ? '#F5F0E8' : 'rgba(199, 107, 74, 0.08)',
          color: step === STEPS.length - 1 ? '#B0A898' : '#C76B4A',
          fontSize: '0.8rem', fontWeight: 500, cursor: step === STEPS.length - 1 ? 'default' : 'pointer',
          fontFamily: "'Source Sans 3', system-ui, sans-serif",
        }}>
          Next &#8594;
        </button>
      </div>
    </div>
  );
}
